apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: web-app     
  namespace: web-app
spec:
  selector:
    matchExpressions:
      - key: deployment  
        operator: In
        values:
        - hello 
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
